# Generated by Django 4.2.1 on 2023-05-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='desc',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='fours',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='singles',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='threes',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='twos',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='imagepname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
