# Generated by Django 4.2.1 on 2023-05-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_images_address_images_desc_images_fours_images_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='onlyimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default=False, max_length=250, null=True, upload_to='images/')),
                ('imagepname', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
