# Generated by Django 4.2.1 on 2023-05-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_onlyimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.RemoveField(
            model_name='images',
            name='imagepname',
        ),
    ]
