# Generated by Django 4.2.1 on 2023-06-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_images_image_remove_images_imagepname'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.FileField(default=False, max_length=250, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='images',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
