# Generated by Django 4.2.1 on 2023-06-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='images',
            new_name='Profile',
        ),
    ]
