# Generated by Django 4.2.1 on 2023-06-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_images_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='occupancy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
